services:
  ratchetup_admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ratchetup_admin
    environment:
      - VIRTUAL_HOST=admin.ratchetup.ai
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=admin.ratchetup.ai
      - LETSENCRYPT_EMAIL=isaac.ochieng2000@gmail.com
    expose:
      - "80"
    networks:
      - proxy
    restart: unless-stopped
networks:
  proxy:
    external: true
